spring:
  application:
    name: producer-app
  datasource:
    url: jdbc:postgresql://localhost:5432/kafka_poc
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:19092},${KAFKA_BOOTSTRAP:localhost:29092},${KAFKA_BOOTSTRAP:localhost:39092}
    schema-registry:
      url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
#    producer:
#      acks: all
#      retries: 10
#      properties:
#        enable.idempotence: true
#        compression.type: lz4
#        linger.ms: 5
#        batch.size: 32768
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    properties:
#      spring.json.add.type.headers: false  # gọn header, dễ liên thông đa ngôn ngữ
#

server:
  port: 5000

# Swagger/OpenAPI 3 Configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /api-docs
    enabled: true
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
