global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'producer-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:5000']
        labels:
          application: 'producer-app'

  - job_name: 'consumer-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:5001']
        labels:
          application: 'consumer-app'

  - job_name: 'consumer-app2'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:5002']
        labels:
          application: 'consumer-app2'
